name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/demo_app:latest
    - name: Push the Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/demo_app:latest
      
    - name: Pull the Docker image
      run: docker pull ${{ secrets.DOCKER_USERNAME }}/demo_app:latest
      
    - name: AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1
    
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: Sentiment-analysis
        environment_name: Sentiment-analysis-env
        version_label: v5
        region: ap-south-1
        docker_image: ${{ secrets.DOCKER_USERNAME }}/demo_app:latest
    
      
      #####Elastic Beanstalk##########################
#     - name: AWS credentials
#       uses: aws-actions/configure-aws-credentials@v1
#       #uses: einaregilsson/beanstalk-deploy@v21
#       with:
#         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         aws-region: ap-south-1
#        # application_name: Sentiment Analysis
#        # environment_name: SentimentAnalysis-env
#        # version_label: 12345
#         #region: ap-south-1
#        # deployment_package: deploy.zip
#     - name: Install AWS EB CLI
#       run: |
#         sudo apt-get update && sudo apt-get install -y python3-pip
#         sudo pip3 install awsebcli
#     - name: Deploy to Elastic Beanstalk
#       run: |
#         eb init -p docker Sentiment-analysis --region ap-south-1
#         eb deploy Sentiment-analysis-env --staged --label "github-actions"
     
    ###################################################
#     - name: Checkout source code
#       uses: actions/checkout@v2

#     - name: Generate deployment package
#       run: zip -r deploy.zip . -x '*.git*'

#     - name: Deploy to EB
#       uses: einaregilsson/beanstalk-deploy@v21
#       with:
#         aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         application_name: Sentiment Analysis
#         environment_name: SentimentAnalysis-env
#         version_label: 12345
#         region: ap-south-1
#         deployment_package: deploy.zip
